//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zit.Client.Proxy.ZitServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZitServices.IZitServices")]
    public interface IZitServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigService/GetAppConfig", ReplyAction="http://tempuri.org/IConfigService/GetAppConfigResponse")]
        Zit.BusinessObjects.BusinessModels.AppConfigClient GetAppConfig();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigService/GetAppConfig", ReplyAction="http://tempuri.org/IConfigService/GetAppConfigResponse")]
        System.Threading.Tasks.Task<Zit.BusinessObjects.BusinessModels.AppConfigClient> GetAppConfigAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/Login", ReplyAction="http://tempuri.org/IZitServices/LoginResponse")]
        Zit.DataTransferObjects.Response<Zit.BusinessObjects.UserContext> Login(int storeId, string userName, string password, string appKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/Login", ReplyAction="http://tempuri.org/IZitServices/LoginResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.UserContext>> LoginAsync(int storeId, string userName, string password, string appKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/CheckAndLogin", ReplyAction="http://tempuri.org/IZitServices/CheckAndLoginResponse")]
        Zit.DataTransferObjects.Response<Zit.BusinessObjects.UserContext> CheckAndLogin(int storeId, string userName, string password, string appKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/CheckAndLogin", ReplyAction="http://tempuri.org/IZitServices/CheckAndLoginResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.UserContext>> CheckAndLoginAsync(int storeId, string userName, string password, string appKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/GetPOSSaleOrderByOrderNo", ReplyAction="http://tempuri.org/IZitServices/GetPOSSaleOrderByOrderNoResponse")]
        Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderModel> GetPOSSaleOrderByOrderNo(string orderNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/GetPOSSaleOrderByOrderNo", ReplyAction="http://tempuri.org/IZitServices/GetPOSSaleOrderByOrderNoResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderModel>> GetPOSSaleOrderByOrderNoAsync(string orderNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/CreatePOSOrderDetailByBarcode", ReplyAction="http://tempuri.org/IZitServices/CreatePOSOrderDetailByBarcodeResponse")]
        Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderDetailModel> CreatePOSOrderDetailByBarcode(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/CreatePOSOrderDetailByBarcode", ReplyAction="http://tempuri.org/IZitServices/CreatePOSOrderDetailByBarcodeResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderDetailModel>> CreatePOSOrderDetailByBarcodeAsync(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/CreateNewPOSOrder", ReplyAction="http://tempuri.org/IZitServices/CreateNewPOSOrderResponse")]
        Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderModel> CreateNewPOSOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/CreateNewPOSOrder", ReplyAction="http://tempuri.org/IZitServices/CreateNewPOSOrderResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderModel>> CreateNewPOSOrderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/SavePOSOrder", ReplyAction="http://tempuri.org/IZitServices/SavePOSOrderResponse")]
        Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderModel> SavePOSOrder(Zit.BusinessObjects.BusinessModels.POSSaleOrderModel order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/SavePOSOrder", ReplyAction="http://tempuri.org/IZitServices/SavePOSOrderResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderModel>> SavePOSOrderAsync(Zit.BusinessObjects.BusinessModels.POSSaleOrderModel order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/SavePOSInfo", ReplyAction="http://tempuri.org/IZitServices/SavePOSInfoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderModel>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderDetailModel>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Obj[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Carrier[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InventoryTransferModel>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InvenrotyTransferDetailModel>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Store[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_SaleReturnReason[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_SaleSource[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.UserContext>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.AppConfigClient))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.POSSaleOrderModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.POSSaleOrderDetailModel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.POSSaleOrderDetailModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.InventoryTransferModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.InvenrotyTransferDetailModel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.InvenrotyTransferDetailModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.Entity.ObservableObjectBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.Entity.EntityBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Enums.SaleChanel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.UserContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Obj[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Obj))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GJ_TranDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GJ_TranDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Acct))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Adj[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Adj))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Store))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_InvTransfer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_InvTransfer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_InvTransferDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_InvTransferDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Barcode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_AdjDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_AdjDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_BarcodeDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_BarcodeDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductVariantAttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_ProductAttribute_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BackInStockSubscription[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BackInStockSubscription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ActivityLog[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ActivityLog))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ActivityLogType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Address))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Affiliate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Affiliate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Address[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShippingMethod[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShippingMethod))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Country[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.StateProvince[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.StateProvince))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Customer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Order[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Order))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.DiscountUsageHistory[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.DiscountUsageHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Discount))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Category[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Category))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Discount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Category_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Category_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.DiscountRequirement[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.DiscountRequirement))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GiftCardUsageHistory[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GiftCardUsageHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GiftCard))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.OrderItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GiftCard[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.OrderItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.OrderNote[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.OrderNote))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RecurringPayment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RecurringPayment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RecurringPaymentHistory[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RecurringPaymentHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RewardPointsHistory[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RewardPointsHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Shipment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Shipment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShipmentItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShipmentItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BlogComment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BlogComment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BlogPost))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Language))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BlogPost[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.LocaleStringResource[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.LocaleStringResource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.LocalizedProperty[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.LocalizedProperty))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.News[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.News))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.NewsComment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.NewsComment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Poll[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Poll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PollAnswer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PollAnswer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PollVotingRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PollVotingRecord))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CustomerRole[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CustomerRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.AclRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.AclRecord))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PermissionRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PermissionRecord))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.TierPrice[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.TierPrice))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ExternalAuthenticationRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ExternalAuthenticationRecord))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Post[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Post))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Topic))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Forum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Group))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Forum[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Topic[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_PrivateMessage[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_PrivateMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Subscription[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Subscription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Log[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Log))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductReview[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductReview))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductReviewHelpfulness[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductReviewHelpfulness))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ReturnRequest[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ReturnRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShoppingCartItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShoppingCartItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Barcode[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductTag[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductTag))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductVariantAttributeCombination[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductVariantAttributeCombination))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Manufacturer_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Manufacturer_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Manufacturer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Picture_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Picture_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Picture))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_ProductAttribute_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_SpecificationAttribute_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_SpecificationAttribute_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.SpecificationAttributeOption))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.SpecificationAttribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.SpecificationAttributeOption[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductAttribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductVariantAttributeValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Transaction[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Transaction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POM_PurchaseInvoiceDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POM_PurchaseInvoiceDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POM_PurchaseInvoice))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POS_SaleOrderDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POS_SaleOrderDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POS_SaleOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Carrier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POS_SaleOrder[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_SaleReturnReason))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_SaleSource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POM_PurchaseInvoice[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GJ_Tran))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Carrier[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Store[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_SaleReturnReason[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_SaleSource[]))]
        Zit.DataTransferObjects.Response SavePOSInfo(Zit.BusinessObjects.BusinessModels.POSSaleOrderModel order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/SavePOSInfo", ReplyAction="http://tempuri.org/IZitServices/SavePOSInfoResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response> SavePOSInfoAsync(Zit.BusinessObjects.BusinessModels.POSSaleOrderModel order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/GetAllObj", ReplyAction="http://tempuri.org/IZitServices/GetAllObjResponse")]
        Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Obj[]> GetAllObj();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/GetAllObj", ReplyAction="http://tempuri.org/IZitServices/GetAllObjResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Obj[]>> GetAllObjAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/GetAllCarrier", ReplyAction="http://tempuri.org/IZitServices/GetAllCarrierResponse")]
        Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Carrier[]> GetAllCarrier();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/GetAllCarrier", ReplyAction="http://tempuri.org/IZitServices/GetAllCarrierResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Carrier[]>> GetAllCarrierAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/UpdatePrintCount", ReplyAction="http://tempuri.org/IZitServices/UpdatePrintCountResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderModel>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderDetailModel>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Obj[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Carrier[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InventoryTransferModel>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InvenrotyTransferDetailModel>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Store[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_SaleReturnReason[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_SaleSource[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.UserContext>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.AppConfigClient))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.POSSaleOrderModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.POSSaleOrderDetailModel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.POSSaleOrderDetailModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.InventoryTransferModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.InvenrotyTransferDetailModel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.InvenrotyTransferDetailModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.Entity.ObservableObjectBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.Entity.EntityBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Enums.SaleChanel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.UserContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Obj[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Obj))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GJ_TranDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GJ_TranDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Acct))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Adj[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Adj))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Store))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_InvTransfer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_InvTransfer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_InvTransferDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_InvTransferDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Barcode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_AdjDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_AdjDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_BarcodeDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_BarcodeDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductVariantAttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_ProductAttribute_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BackInStockSubscription[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BackInStockSubscription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ActivityLog[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ActivityLog))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ActivityLogType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Address))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Affiliate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Affiliate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Address[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShippingMethod[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShippingMethod))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Country[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.StateProvince[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.StateProvince))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Customer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Order[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Order))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.DiscountUsageHistory[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.DiscountUsageHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Discount))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Category[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Category))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Discount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Category_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Category_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.DiscountRequirement[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.DiscountRequirement))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GiftCardUsageHistory[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GiftCardUsageHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GiftCard))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.OrderItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GiftCard[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.OrderItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.OrderNote[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.OrderNote))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RecurringPayment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RecurringPayment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RecurringPaymentHistory[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RecurringPaymentHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RewardPointsHistory[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RewardPointsHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Shipment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Shipment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShipmentItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShipmentItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BlogComment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BlogComment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BlogPost))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Language))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BlogPost[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.LocaleStringResource[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.LocaleStringResource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.LocalizedProperty[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.LocalizedProperty))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.News[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.News))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.NewsComment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.NewsComment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Poll[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Poll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PollAnswer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PollAnswer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PollVotingRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PollVotingRecord))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CustomerRole[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CustomerRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.AclRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.AclRecord))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PermissionRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PermissionRecord))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.TierPrice[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.TierPrice))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ExternalAuthenticationRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ExternalAuthenticationRecord))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Post[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Post))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Topic))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Forum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Group))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Forum[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Topic[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_PrivateMessage[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_PrivateMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Subscription[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Subscription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Log[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Log))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductReview[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductReview))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductReviewHelpfulness[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductReviewHelpfulness))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ReturnRequest[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ReturnRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShoppingCartItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShoppingCartItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Barcode[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductTag[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductTag))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductVariantAttributeCombination[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductVariantAttributeCombination))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Manufacturer_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Manufacturer_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Manufacturer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Picture_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Picture_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Picture))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_ProductAttribute_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_SpecificationAttribute_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_SpecificationAttribute_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.SpecificationAttributeOption))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.SpecificationAttribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.SpecificationAttributeOption[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductAttribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductVariantAttributeValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Transaction[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Transaction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POM_PurchaseInvoiceDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POM_PurchaseInvoiceDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POM_PurchaseInvoice))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POS_SaleOrderDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POS_SaleOrderDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POS_SaleOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Carrier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POS_SaleOrder[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_SaleReturnReason))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_SaleSource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POM_PurchaseInvoice[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GJ_Tran))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Carrier[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Store[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_SaleReturnReason[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_SaleSource[]))]
        Zit.DataTransferObjects.Response UpdatePrintCount(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/UpdatePrintCount", ReplyAction="http://tempuri.org/IZitServices/UpdatePrintCountResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response> UpdatePrintCountAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/CreateNewTransfer", ReplyAction="http://tempuri.org/IZitServices/CreateNewTransferResponse")]
        Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InventoryTransferModel> CreateNewTransfer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/CreateNewTransfer", ReplyAction="http://tempuri.org/IZitServices/CreateNewTransferResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InventoryTransferModel>> CreateNewTransferAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/CreateITDetailByBarcode", ReplyAction="http://tempuri.org/IZitServices/CreateITDetailByBarcodeResponse")]
        Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InvenrotyTransferDetailModel> CreateITDetailByBarcode(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/CreateITDetailByBarcode", ReplyAction="http://tempuri.org/IZitServices/CreateITDetailByBarcodeResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InvenrotyTransferDetailModel>> CreateITDetailByBarcodeAsync(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/SaveInvTransfer", ReplyAction="http://tempuri.org/IZitServices/SaveInvTransferResponse")]
        Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InventoryTransferModel> SaveInvTransfer(Zit.BusinessObjects.BusinessModels.InventoryTransferModel transfer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/SaveInvTransfer", ReplyAction="http://tempuri.org/IZitServices/SaveInvTransferResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InventoryTransferModel>> SaveInvTransferAsync(Zit.BusinessObjects.BusinessModels.InventoryTransferModel transfer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/GetInvTransferByTransferNo", ReplyAction="http://tempuri.org/IZitServices/GetInvTransferByTransferNoResponse")]
        Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InventoryTransferModel> GetInvTransferByTransferNo(string transferNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/GetInvTransferByTransferNo", ReplyAction="http://tempuri.org/IZitServices/GetInvTransferByTransferNoResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InventoryTransferModel>> GetInvTransferByTransferNoAsync(string transferNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/GetAllStore", ReplyAction="http://tempuri.org/IZitServices/GetAllStoreResponse")]
        Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Store[]> GetAllStore();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/GetAllStore", ReplyAction="http://tempuri.org/IZitServices/GetAllStoreResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Store[]>> GetAllStoreAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/UserCheckTime", ReplyAction="http://tempuri.org/IZitServices/UserCheckTimeResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderModel>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderDetailModel>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Obj[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Carrier[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InventoryTransferModel>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InvenrotyTransferDetailModel>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Store[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_SaleReturnReason[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_SaleSource[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.UserContext>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.AppConfigClient))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.POSSaleOrderModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.POSSaleOrderDetailModel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.POSSaleOrderDetailModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.InventoryTransferModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.InvenrotyTransferDetailModel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.InvenrotyTransferDetailModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.Entity.ObservableObjectBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.Entity.EntityBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Enums.SaleChanel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.UserContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Obj[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Obj))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GJ_TranDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GJ_TranDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Acct))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Adj[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Adj))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Store))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_InvTransfer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_InvTransfer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_InvTransferDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_InvTransferDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Barcode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_AdjDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_AdjDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_BarcodeDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_BarcodeDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductVariantAttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_ProductAttribute_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BackInStockSubscription[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BackInStockSubscription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ActivityLog[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ActivityLog))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ActivityLogType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Address))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Affiliate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Affiliate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Address[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShippingMethod[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShippingMethod))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Country[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.StateProvince[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.StateProvince))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Customer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Order[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Order))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.DiscountUsageHistory[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.DiscountUsageHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Discount))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Category[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Category))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Discount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Category_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Category_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.DiscountRequirement[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.DiscountRequirement))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GiftCardUsageHistory[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GiftCardUsageHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GiftCard))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.OrderItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GiftCard[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.OrderItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.OrderNote[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.OrderNote))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RecurringPayment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RecurringPayment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RecurringPaymentHistory[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RecurringPaymentHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RewardPointsHistory[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RewardPointsHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Shipment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Shipment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShipmentItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShipmentItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BlogComment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BlogComment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BlogPost))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Language))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BlogPost[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.LocaleStringResource[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.LocaleStringResource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.LocalizedProperty[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.LocalizedProperty))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.News[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.News))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.NewsComment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.NewsComment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Poll[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Poll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PollAnswer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PollAnswer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PollVotingRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PollVotingRecord))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CustomerRole[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CustomerRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.AclRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.AclRecord))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PermissionRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PermissionRecord))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.TierPrice[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.TierPrice))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ExternalAuthenticationRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ExternalAuthenticationRecord))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Post[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Post))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Topic))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Forum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Group))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Forum[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Topic[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_PrivateMessage[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_PrivateMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Subscription[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Subscription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Log[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Log))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductReview[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductReview))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductReviewHelpfulness[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductReviewHelpfulness))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ReturnRequest[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ReturnRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShoppingCartItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShoppingCartItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Barcode[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductTag[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductTag))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductVariantAttributeCombination[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductVariantAttributeCombination))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Manufacturer_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Manufacturer_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Manufacturer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Picture_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Picture_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Picture))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_ProductAttribute_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_SpecificationAttribute_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_SpecificationAttribute_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.SpecificationAttributeOption))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.SpecificationAttribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.SpecificationAttributeOption[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductAttribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductVariantAttributeValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Transaction[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Transaction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POM_PurchaseInvoiceDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POM_PurchaseInvoiceDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POM_PurchaseInvoice))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POS_SaleOrderDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POS_SaleOrderDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POS_SaleOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Carrier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POS_SaleOrder[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_SaleReturnReason))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_SaleSource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POM_PurchaseInvoice[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GJ_Tran))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Carrier[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Store[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_SaleReturnReason[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_SaleSource[]))]
        Zit.DataTransferObjects.Response UserCheckTime(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/UserCheckTime", ReplyAction="http://tempuri.org/IZitServices/UserCheckTimeResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response> UserCheckTimeAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/GetUserByName", ReplyAction="http://tempuri.org/IZitServices/GetUserByNameResponse")]
        Zit.DataTransferObjects.Response<string> GetUserByName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/GetUserByName", ReplyAction="http://tempuri.org/IZitServices/GetUserByNameResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<string>> GetUserByNameAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/UpdateUser", ReplyAction="http://tempuri.org/IZitServices/UpdateUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderModel>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderDetailModel>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Obj[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Carrier[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InventoryTransferModel>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InvenrotyTransferDetailModel>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Store[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_SaleReturnReason[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_SaleSource[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.DataTransferObjects.Response<Zit.BusinessObjects.UserContext>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.AppConfigClient))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.POSSaleOrderModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.POSSaleOrderDetailModel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.POSSaleOrderDetailModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.InventoryTransferModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.InvenrotyTransferDetailModel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BusinessModels.InvenrotyTransferDetailModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.Entity.ObservableObjectBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.Entity.EntityBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Enums.SaleChanel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.UserContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Obj[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Obj))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GJ_TranDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GJ_TranDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Acct))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Adj[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Adj))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Store))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_InvTransfer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_InvTransfer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_InvTransferDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_InvTransferDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Barcode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_AdjDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_AdjDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_BarcodeDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_BarcodeDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductVariantAttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_ProductAttribute_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BackInStockSubscription[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BackInStockSubscription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ActivityLog[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ActivityLog))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ActivityLogType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Address))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Affiliate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Affiliate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Address[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShippingMethod[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShippingMethod))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Country[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.StateProvince[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.StateProvince))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Customer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Order[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Order))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.DiscountUsageHistory[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.DiscountUsageHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Discount))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Category[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Category))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Discount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Category_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Category_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.DiscountRequirement[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.DiscountRequirement))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GiftCardUsageHistory[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GiftCardUsageHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GiftCard))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.OrderItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GiftCard[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.OrderItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.OrderNote[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.OrderNote))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RecurringPayment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RecurringPayment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RecurringPaymentHistory[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RecurringPaymentHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RewardPointsHistory[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.RewardPointsHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Shipment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Shipment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShipmentItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShipmentItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BlogComment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BlogComment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BlogPost))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Language))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.BlogPost[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.LocaleStringResource[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.LocaleStringResource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.LocalizedProperty[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.LocalizedProperty))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.News[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.News))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.NewsComment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.NewsComment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Poll[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Poll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PollAnswer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PollAnswer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PollVotingRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PollVotingRecord))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CustomerRole[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CustomerRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.AclRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.AclRecord))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PermissionRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.PermissionRecord))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.TierPrice[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.TierPrice))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ExternalAuthenticationRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ExternalAuthenticationRecord))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Post[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Post))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Topic))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Forum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Group))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Forum[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Topic[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_PrivateMessage[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_PrivateMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Subscription[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Forums_Subscription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Log[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Log))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductReview[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductReview))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductReviewHelpfulness[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductReviewHelpfulness))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ReturnRequest[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ReturnRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShoppingCartItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ShoppingCartItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Barcode[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductTag[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductTag))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductVariantAttributeCombination[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductVariantAttributeCombination))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Manufacturer_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Manufacturer_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Manufacturer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Picture_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_Picture_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Picture))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_ProductAttribute_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_SpecificationAttribute_Mapping[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.Product_SpecificationAttribute_Mapping))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.SpecificationAttributeOption))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.SpecificationAttribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.SpecificationAttributeOption[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductAttribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.ProductVariantAttributeValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Transaction[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.IVM_Transaction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POM_PurchaseInvoiceDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POM_PurchaseInvoiceDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POM_PurchaseInvoice))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POS_SaleOrderDetail[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POS_SaleOrderDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POS_SaleOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Carrier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POS_SaleOrder[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_SaleReturnReason))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_SaleSource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.POM_PurchaseInvoice[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.GJ_Tran))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Carrier[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_Store[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_SaleReturnReason[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Zit.BusinessObjects.CF_SaleSource[]))]
        Zit.DataTransferObjects.Response UpdateUser(string userName, string fullName, string password, bool isActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/UpdateUser", ReplyAction="http://tempuri.org/IZitServices/UpdateUserResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response> UpdateUserAsync(string userName, string fullName, string password, bool isActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/GetAllSaleReturnReason", ReplyAction="http://tempuri.org/IZitServices/GetAllSaleReturnReasonResponse")]
        Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_SaleReturnReason[]> GetAllSaleReturnReason();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/GetAllSaleReturnReason", ReplyAction="http://tempuri.org/IZitServices/GetAllSaleReturnReasonResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_SaleReturnReason[]>> GetAllSaleReturnReasonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/GetAllSaleSource", ReplyAction="http://tempuri.org/IZitServices/GetAllSaleSourceResponse")]
        Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_SaleSource[]> GetAllSaleSource();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZitServices/GetAllSaleSource", ReplyAction="http://tempuri.org/IZitServices/GetAllSaleSourceResponse")]
        System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_SaleSource[]>> GetAllSaleSourceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZitServicesChannel : Zit.Client.Proxy.ZitServices.IZitServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZitServicesClient : System.ServiceModel.ClientBase<Zit.Client.Proxy.ZitServices.IZitServices>, Zit.Client.Proxy.ZitServices.IZitServices {
        
        public ZitServicesClient() {
        }
        
        public ZitServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZitServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZitServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZitServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Zit.BusinessObjects.BusinessModels.AppConfigClient GetAppConfig() {
            return base.Channel.GetAppConfig();
        }
        
        public System.Threading.Tasks.Task<Zit.BusinessObjects.BusinessModels.AppConfigClient> GetAppConfigAsync() {
            return base.Channel.GetAppConfigAsync();
        }
        
        public Zit.DataTransferObjects.Response<Zit.BusinessObjects.UserContext> Login(int storeId, string userName, string password, string appKey) {
            return base.Channel.Login(storeId, userName, password, appKey);
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.UserContext>> LoginAsync(int storeId, string userName, string password, string appKey) {
            return base.Channel.LoginAsync(storeId, userName, password, appKey);
        }
        
        public Zit.DataTransferObjects.Response<Zit.BusinessObjects.UserContext> CheckAndLogin(int storeId, string userName, string password, string appKey) {
            return base.Channel.CheckAndLogin(storeId, userName, password, appKey);
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.UserContext>> CheckAndLoginAsync(int storeId, string userName, string password, string appKey) {
            return base.Channel.CheckAndLoginAsync(storeId, userName, password, appKey);
        }
        
        public Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderModel> GetPOSSaleOrderByOrderNo(string orderNo) {
            return base.Channel.GetPOSSaleOrderByOrderNo(orderNo);
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderModel>> GetPOSSaleOrderByOrderNoAsync(string orderNo) {
            return base.Channel.GetPOSSaleOrderByOrderNoAsync(orderNo);
        }
        
        public Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderDetailModel> CreatePOSOrderDetailByBarcode(string barcode) {
            return base.Channel.CreatePOSOrderDetailByBarcode(barcode);
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderDetailModel>> CreatePOSOrderDetailByBarcodeAsync(string barcode) {
            return base.Channel.CreatePOSOrderDetailByBarcodeAsync(barcode);
        }
        
        public Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderModel> CreateNewPOSOrder() {
            return base.Channel.CreateNewPOSOrder();
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderModel>> CreateNewPOSOrderAsync() {
            return base.Channel.CreateNewPOSOrderAsync();
        }
        
        public Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderModel> SavePOSOrder(Zit.BusinessObjects.BusinessModels.POSSaleOrderModel order) {
            return base.Channel.SavePOSOrder(order);
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.POSSaleOrderModel>> SavePOSOrderAsync(Zit.BusinessObjects.BusinessModels.POSSaleOrderModel order) {
            return base.Channel.SavePOSOrderAsync(order);
        }
        
        public Zit.DataTransferObjects.Response SavePOSInfo(Zit.BusinessObjects.BusinessModels.POSSaleOrderModel order) {
            return base.Channel.SavePOSInfo(order);
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response> SavePOSInfoAsync(Zit.BusinessObjects.BusinessModels.POSSaleOrderModel order) {
            return base.Channel.SavePOSInfoAsync(order);
        }
        
        public Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Obj[]> GetAllObj() {
            return base.Channel.GetAllObj();
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Obj[]>> GetAllObjAsync() {
            return base.Channel.GetAllObjAsync();
        }
        
        public Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Carrier[]> GetAllCarrier() {
            return base.Channel.GetAllCarrier();
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Carrier[]>> GetAllCarrierAsync() {
            return base.Channel.GetAllCarrierAsync();
        }
        
        public Zit.DataTransferObjects.Response UpdatePrintCount(int orderId) {
            return base.Channel.UpdatePrintCount(orderId);
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response> UpdatePrintCountAsync(int orderId) {
            return base.Channel.UpdatePrintCountAsync(orderId);
        }
        
        public Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InventoryTransferModel> CreateNewTransfer() {
            return base.Channel.CreateNewTransfer();
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InventoryTransferModel>> CreateNewTransferAsync() {
            return base.Channel.CreateNewTransferAsync();
        }
        
        public Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InvenrotyTransferDetailModel> CreateITDetailByBarcode(string barcode) {
            return base.Channel.CreateITDetailByBarcode(barcode);
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InvenrotyTransferDetailModel>> CreateITDetailByBarcodeAsync(string barcode) {
            return base.Channel.CreateITDetailByBarcodeAsync(barcode);
        }
        
        public Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InventoryTransferModel> SaveInvTransfer(Zit.BusinessObjects.BusinessModels.InventoryTransferModel transfer) {
            return base.Channel.SaveInvTransfer(transfer);
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InventoryTransferModel>> SaveInvTransferAsync(Zit.BusinessObjects.BusinessModels.InventoryTransferModel transfer) {
            return base.Channel.SaveInvTransferAsync(transfer);
        }
        
        public Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InventoryTransferModel> GetInvTransferByTransferNo(string transferNo) {
            return base.Channel.GetInvTransferByTransferNo(transferNo);
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.BusinessModels.InventoryTransferModel>> GetInvTransferByTransferNoAsync(string transferNo) {
            return base.Channel.GetInvTransferByTransferNoAsync(transferNo);
        }
        
        public Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Store[]> GetAllStore() {
            return base.Channel.GetAllStore();
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_Store[]>> GetAllStoreAsync() {
            return base.Channel.GetAllStoreAsync();
        }
        
        public Zit.DataTransferObjects.Response UserCheckTime(string userName, string password) {
            return base.Channel.UserCheckTime(userName, password);
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response> UserCheckTimeAsync(string userName, string password) {
            return base.Channel.UserCheckTimeAsync(userName, password);
        }
        
        public Zit.DataTransferObjects.Response<string> GetUserByName(string userName) {
            return base.Channel.GetUserByName(userName);
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<string>> GetUserByNameAsync(string userName) {
            return base.Channel.GetUserByNameAsync(userName);
        }
        
        public Zit.DataTransferObjects.Response UpdateUser(string userName, string fullName, string password, bool isActive) {
            return base.Channel.UpdateUser(userName, fullName, password, isActive);
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response> UpdateUserAsync(string userName, string fullName, string password, bool isActive) {
            return base.Channel.UpdateUserAsync(userName, fullName, password, isActive);
        }
        
        public Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_SaleReturnReason[]> GetAllSaleReturnReason() {
            return base.Channel.GetAllSaleReturnReason();
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_SaleReturnReason[]>> GetAllSaleReturnReasonAsync() {
            return base.Channel.GetAllSaleReturnReasonAsync();
        }
        
        public Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_SaleSource[]> GetAllSaleSource() {
            return base.Channel.GetAllSaleSource();
        }
        
        public System.Threading.Tasks.Task<Zit.DataTransferObjects.Response<Zit.BusinessObjects.CF_SaleSource[]>> GetAllSaleSourceAsync() {
            return base.Channel.GetAllSaleSourceAsync();
        }
    }
}
