//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zit.BusinessObjects
{
    using Zit.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class CF_Carrier : EntityBase
    {
        public CF_Carrier()
        {
            this.POS_SaleOrder = new HashSet<POS_SaleOrder>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int AcctId { get; set; }
    
        public virtual ICollection<POS_SaleOrder> POS_SaleOrder { get; set; }
    }
}
