//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zit.BusinessObjects
{
    using Zit.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class CF_Store : EntityBase
    {
        public CF_Store()
        {
            this.IVM_Adj = new HashSet<IVM_Adj>();
            this.IVM_InvTransfer = new HashSet<IVM_InvTransfer>();
            this.IVM_InvTransfer1 = new HashSet<IVM_InvTransfer>();
            this.IVM_Transaction = new HashSet<IVM_Transaction>();
            this.POM_PurchaseInvoice = new HashSet<POM_PurchaseInvoice>();
            this.POS_SaleOrder = new HashSet<POS_SaleOrder>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Code { get; set; }
        public Nullable<int> InvAcctId { get; set; }
        public Nullable<int> CashAcctId { get; set; }
        public Nullable<int> RevAcctId { get; set; }
        public Nullable<int> SoldCostAcctId { get; set; }
    
        public virtual ICollection<IVM_Adj> IVM_Adj { get; set; }
        public virtual ICollection<IVM_InvTransfer> IVM_InvTransfer { get; set; }
        public virtual ICollection<IVM_InvTransfer> IVM_InvTransfer1 { get; set; }
        public virtual ICollection<IVM_Transaction> IVM_Transaction { get; set; }
        public virtual ICollection<POM_PurchaseInvoice> POM_PurchaseInvoice { get; set; }
        public virtual ICollection<POS_SaleOrder> POS_SaleOrder { get; set; }
    }
}
