//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zit.BusinessObjects
{
    using Zit.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class Country : EntityBase
    {
        public Country()
        {
            this.Address = new HashSet<Address>();
            this.StateProvince = new HashSet<StateProvince>();
            this.ShippingMethod = new HashSet<ShippingMethod>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool AllowsBilling { get; set; }
        public bool AllowsShipping { get; set; }
        public string TwoLetterIsoCode { get; set; }
        public string ThreeLetterIsoCode { get; set; }
        public int NumericIsoCode { get; set; }
        public bool SubjectToVat { get; set; }
        public bool Published { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<StateProvince> StateProvince { get; set; }
        public virtual ICollection<ShippingMethod> ShippingMethod { get; set; }
    }
}
