//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zit.BusinessObjects
{
    using Zit.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRole : EntityBase
    {
        public CustomerRole()
        {
            this.AclRecord = new HashSet<AclRecord>();
            this.TierPrice = new HashSet<TierPrice>();
            this.Customer = new HashSet<Customer>();
            this.PermissionRecord = new HashSet<PermissionRecord>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool FreeShipping { get; set; }
        public bool TaxExempt { get; set; }
        public bool Active { get; set; }
        public bool IsSystemRole { get; set; }
        public string SystemName { get; set; }
    
        public virtual ICollection<AclRecord> AclRecord { get; set; }
        public virtual ICollection<TierPrice> TierPrice { get; set; }
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual ICollection<PermissionRecord> PermissionRecord { get; set; }
    }
}
