//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zit.BusinessObjects
{
    using Zit.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class GJ_TranDetail : EntityBase
    {
        public int Id { get; set; }
        public int TransId { get; set; }
        public int LineId { get; set; }
        public int AcctId { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public Nullable<int> RefObjId { get; set; }
        public string Desc { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] VersionNo { get; set; }
    
        public virtual CF_Acct CF_Acct { get; set; }
        public virtual CF_Obj CF_Obj { get; set; }
        public virtual GJ_Tran GJ_Tran { get; set; }
    }
}
