//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zit.BusinessObjects
{
    using Zit.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class IVM_BarcodeDetail : EntityBase
    {
        public int Id { get; set; }
        public int BarcodeId { get; set; }
        public int ProductVariantAttributeValueId { get; set; }
    
        public virtual IVM_Barcode IVM_Barcode { get; set; }
        public virtual ProductVariantAttributeValue ProductVariantAttributeValue { get; set; }
    }
}
