//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zit.BusinessObjects
{
    using Zit.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class POS_SaleOrder : EntityBase
    {
        public POS_SaleOrder()
        {
            this.POS_SaleOrderDetail = new HashSet<POS_SaleOrderDetail>();
        }
    
        public int Id { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Desc { get; set; }
        public int ChanelId { get; set; }
        public string RefNo { get; set; }
        public decimal SubTotal { get; set; }
        public decimal ShippingFee { get; set; }
        public decimal Amount { get; set; }
        public decimal ReceiveMoney { get; set; }
        public decimal ReturnMoney { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] VersionNo { get; set; }
        public string Mobile { get; set; }
        public string CustomerName { get; set; }
        public decimal DiscountPercent { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal Discount { get; set; }
        public int Status { get; set; }
        public Nullable<int> DebitAcctId { get; set; }
        public Nullable<int> ObjId { get; set; }
        public Nullable<int> FeeAcctId { get; set; }
        public decimal FeeAmount { get; set; }
        public int StoreId { get; set; }
        public Nullable<int> CarrierId { get; set; }
        public decimal AeroShippingFee { get; set; }
        public int PrintCount { get; set; }
        public string Users { get; set; }
        public bool IsMasterCard { get; set; }
        public int SourceId { get; set; }
        public Nullable<int> ReturnReasonId { get; set; }
        public string ShippingCode { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual CF_Carrier CF_Carrier { get; set; }
        public virtual CF_Obj CF_Obj { get; set; }
        public virtual CF_SaleReturnReason CF_SaleReturnReason { get; set; }
        public virtual CF_SaleSource CF_SaleSource { get; set; }
        public virtual CF_Store CF_Store { get; set; }
        public virtual ICollection<POS_SaleOrderDetail> POS_SaleOrderDetail { get; set; }
    }
}
