//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zit.BusinessObjects
{
    using Zit.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class POS_SaleOrderDetail : EntityBase
    {
        public int Id { get; set; }
        public int SaleOrderId { get; set; }
        public int Seq { get; set; }
        public int BarcodeId { get; set; }
        public int Qty { get; set; }
        public decimal SellUnitPrice { get; set; }
        public int LineDiscount { get; set; }
        public decimal LineAmount { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] VersionNo { get; set; }
    
        public virtual IVM_Barcode IVM_Barcode { get; set; }
        public virtual POS_SaleOrder POS_SaleOrder { get; set; }
    }
}
