//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zit.BusinessObjects
{
    using Zit.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class Seq_Group : EntityBase
    {
        public int SeqGroupID { get; set; }
        public string Code { get; set; }
        public int LastNumber { get; set; }
        public Nullable<int> SeqNoID { get; set; }
        public string PrefixGroup { get; set; }
    
        public virtual Seq_No Seq_No { get; set; }
    }
}
