//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zit.BusinessObjects
{
    using Zit.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_User : EntityBase
    {
        public SYS_User()
        {
            this.HR_UserCheckTime = new HashSet<HR_UserCheckTime>();
            this.SYS_UserRole = new HashSet<SYS_UserRole>();
        }
    
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string CellPhone { get; set; }
        public int Status { get; set; }
        public Nullable<int> UserType { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] VersionNo { get; set; }
        public int AppID { get; set; }
    
        public virtual ICollection<HR_UserCheckTime> HR_UserCheckTime { get; set; }
        public virtual SYS_Apps SYS_Apps { get; set; }
        public virtual ICollection<SYS_UserRole> SYS_UserRole { get; set; }
    }
}
