//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zit.BusinessObjects
{
    using Zit.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Function : EntityBase
    {
        public SYS_Function()
        {
            this.SYS_AppFunction = new HashSet<SYS_AppFunction>();
            this.SYS_RoleFunction = new HashSet<SYS_RoleFunction>();
            this.SYS_ViewFunction = new HashSet<SYS_ViewFunction>();
        }
    
        public int FunctionID { get; set; }
        public string FunctionCode { get; set; }
        public string FunctionName { get; set; }
        public bool Enable { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] VersionNo { get; set; }
    
        public virtual ICollection<SYS_AppFunction> SYS_AppFunction { get; set; }
        public virtual ICollection<SYS_RoleFunction> SYS_RoleFunction { get; set; }
        public virtual ICollection<SYS_ViewFunction> SYS_ViewFunction { get; set; }
    }
}
