//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zit.BusinessObjects
{
    using Zit.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Apps : EntityBase
    {
        public SYS_Apps()
        {
            this.SYS_AppFunction = new HashSet<SYS_AppFunction>();
            this.SYS_User = new HashSet<SYS_User>();
        }
    
        public int AppID { get; set; }
        public string AppName { get; set; }
        public string AppKey { get; set; }
        public bool Enable { get; set; }
        public bool AllFunctions { get; set; }
    
        public virtual ICollection<SYS_AppFunction> SYS_AppFunction { get; set; }
        public virtual ICollection<SYS_User> SYS_User { get; set; }
    }
}
