//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zit.BusinessObjects
{
    using Zit.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Role : EntityBase
    {
        public SYS_Role()
        {
            this.SYS_RoleFunction = new HashSet<SYS_RoleFunction>();
            this.SYS_UserRole = new HashSet<SYS_UserRole>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public bool Enable { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] VersionNo { get; set; }
        public int RoleType { get; set; }
    
        public virtual ICollection<SYS_RoleFunction> SYS_RoleFunction { get; set; }
        public virtual ICollection<SYS_UserRole> SYS_UserRole { get; set; }
    }
}
