//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zit.BusinessObjects
{
    using Zit.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Menu : EntityBase
    {
        public SYS_Menu()
        {
            this.SYS_Menu1 = new HashSet<SYS_Menu>();
        }
    
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public int MenuOrder { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> ViewID { get; set; }
        public Nullable<bool> Enable { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] VersionNo { get; set; }
    
        public virtual ICollection<SYS_Menu> SYS_Menu1 { get; set; }
        public virtual SYS_Menu SYS_Menu2 { get; set; }
        public virtual SYS_View SYS_View { get; set; }
    }
}
