//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zit.BusinessObjects
{
    using Zit.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_View : EntityBase
    {
        public SYS_View()
        {
            this.SYS_Menu = new HashSet<SYS_Menu>();
            this.SYS_View1 = new HashSet<SYS_View>();
            this.SYS_ViewFunction = new HashSet<SYS_ViewFunction>();
        }
    
        public int ViewID { get; set; }
        public string ViewName { get; set; }
        public string Url { get; set; }
        public bool Enable { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] VersionNo { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual ICollection<SYS_Menu> SYS_Menu { get; set; }
        public virtual ICollection<SYS_View> SYS_View1 { get; set; }
        public virtual SYS_View SYS_View2 { get; set; }
        public virtual ICollection<SYS_ViewFunction> SYS_ViewFunction { get; set; }
    }
}
