//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zit.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataEntities : DbContext
    {
        public DataEntities()
            : base("name=DataEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
    		this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    	/*
        public DbSet<AclRecord> AclRecord { get; set; }
        public DbSet<ActivityLog> ActivityLog { get; set; }
        public DbSet<ActivityLogType> ActivityLogType { get; set; }
        public DbSet<Address> Address { get; set; }
        public DbSet<Affiliate> Affiliate { get; set; }
        public DbSet<BackInStockSubscription> BackInStockSubscription { get; set; }
        public DbSet<BlogComment> BlogComment { get; set; }
        public DbSet<BlogPost> BlogPost { get; set; }
        public DbSet<Campaign> Campaign { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<CategoryTemplate> CategoryTemplate { get; set; }
        public DbSet<CF_Acct> CF_Acct { get; set; }
        public DbSet<CF_Carrier> CF_Carrier { get; set; }
        public DbSet<CF_Obj> CF_Obj { get; set; }
        public DbSet<CF_SaleReturnReason> CF_SaleReturnReason { get; set; }
        public DbSet<CF_SaleSource> CF_SaleSource { get; set; }
        public DbSet<CF_Store> CF_Store { get; set; }
        public DbSet<CheckoutAttribute> CheckoutAttribute { get; set; }
        public DbSet<CheckoutAttributeValue> CheckoutAttributeValue { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<CrossSellProduct> CrossSellProduct { get; set; }
        public DbSet<Currency> Currency { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<CustomerRole> CustomerRole { get; set; }
        public DbSet<DeliveryDate> DeliveryDate { get; set; }
        public DbSet<Discount> Discount { get; set; }
        public DbSet<DiscountRequirement> DiscountRequirement { get; set; }
        public DbSet<DiscountUsageHistory> DiscountUsageHistory { get; set; }
        public DbSet<Download> Download { get; set; }
        public DbSet<EmailAccount> EmailAccount { get; set; }
        public DbSet<ExternalAuthenticationRecord> ExternalAuthenticationRecord { get; set; }
        public DbSet<Forums_Forum> Forums_Forum { get; set; }
        public DbSet<Forums_Group> Forums_Group { get; set; }
        public DbSet<Forums_Post> Forums_Post { get; set; }
        public DbSet<Forums_PrivateMessage> Forums_PrivateMessage { get; set; }
        public DbSet<Forums_Subscription> Forums_Subscription { get; set; }
        public DbSet<Forums_Topic> Forums_Topic { get; set; }
        public DbSet<GenericAttribute> GenericAttribute { get; set; }
        public DbSet<GiftCard> GiftCard { get; set; }
        public DbSet<GiftCardUsageHistory> GiftCardUsageHistory { get; set; }
        public DbSet<GJ_Tran> GJ_Tran { get; set; }
        public DbSet<GJ_TranDetail> GJ_TranDetail { get; set; }
        public DbSet<GoogleProduct> GoogleProduct { get; set; }
        public DbSet<HR_UserCheckTime> HR_UserCheckTime { get; set; }
        public DbSet<IVM_Adj> IVM_Adj { get; set; }
        public DbSet<IVM_Barcode> IVM_Barcode { get; set; }
        public DbSet<IVM_BarcodeDetail> IVM_BarcodeDetail { get; set; }
        public DbSet<IVM_InvTransfer> IVM_InvTransfer { get; set; }
        public DbSet<IVM_InvTransferDetail> IVM_InvTransferDetail { get; set; }
        public DbSet<IVM_Transaction> IVM_Transaction { get; set; }
        public DbSet<Language> Language { get; set; }
        public DbSet<LocaleStringResource> LocaleStringResource { get; set; }
        public DbSet<LocalizedProperty> LocalizedProperty { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<Manufacturer> Manufacturer { get; set; }
        public DbSet<ManufacturerTemplate> ManufacturerTemplate { get; set; }
        public DbSet<MeasureDimension> MeasureDimension { get; set; }
        public DbSet<MeasureWeight> MeasureWeight { get; set; }
        public DbSet<MessageTemplate> MessageTemplate { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<NewsComment> NewsComment { get; set; }
        public DbSet<NewsLetterSubscription> NewsLetterSubscription { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderItem> OrderItem { get; set; }
        public DbSet<OrderNote> OrderNote { get; set; }
        public DbSet<PermissionRecord> PermissionRecord { get; set; }
        public DbSet<Picture> Picture { get; set; }
        public DbSet<Poll> Poll { get; set; }
        public DbSet<PollAnswer> PollAnswer { get; set; }
        public DbSet<PollVotingRecord> PollVotingRecord { get; set; }
        public DbSet<POM_PurchaseInvoice> POM_PurchaseInvoice { get; set; }
        public DbSet<POM_PurchaseInvoiceDetail> POM_PurchaseInvoiceDetail { get; set; }
        public DbSet<POS_SaleOrderDetail> POS_SaleOrderDetail { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<Product_Category_Mapping> Product_Category_Mapping { get; set; }
        public DbSet<Product_Manufacturer_Mapping> Product_Manufacturer_Mapping { get; set; }
        public DbSet<Product_Picture_Mapping> Product_Picture_Mapping { get; set; }
        public DbSet<Product_ProductAttribute_Mapping> Product_ProductAttribute_Mapping { get; set; }
        public DbSet<Product_SpecificationAttribute_Mapping> Product_SpecificationAttribute_Mapping { get; set; }
        public DbSet<ProductAttribute> ProductAttribute { get; set; }
        public DbSet<ProductReview> ProductReview { get; set; }
        public DbSet<ProductReviewHelpfulness> ProductReviewHelpfulness { get; set; }
        public DbSet<ProductTag> ProductTag { get; set; }
        public DbSet<ProductTemplate> ProductTemplate { get; set; }
        public DbSet<ProductVariantAttributeCombination> ProductVariantAttributeCombination { get; set; }
        public DbSet<ProductVariantAttributeValue> ProductVariantAttributeValue { get; set; }
        public DbSet<QueuedEmail> QueuedEmail { get; set; }
        public DbSet<RecurringPayment> RecurringPayment { get; set; }
        public DbSet<RecurringPaymentHistory> RecurringPaymentHistory { get; set; }
        public DbSet<RelatedProduct> RelatedProduct { get; set; }
        public DbSet<ReturnRequest> ReturnRequest { get; set; }
        public DbSet<RewardPointsHistory> RewardPointsHistory { get; set; }
        public DbSet<ScheduleTask> ScheduleTask { get; set; }
        public DbSet<SearchTerm> SearchTerm { get; set; }
        public DbSet<Seq_Group> Seq_Group { get; set; }
        public DbSet<Seq_No> Seq_No { get; set; }
        public DbSet<Setting> Setting { get; set; }
        public DbSet<Shipment> Shipment { get; set; }
        public DbSet<ShipmentItem> ShipmentItem { get; set; }
        public DbSet<ShippingByWeight> ShippingByWeight { get; set; }
        public DbSet<ShippingMethod> ShippingMethod { get; set; }
        public DbSet<ShoppingCartItem> ShoppingCartItem { get; set; }
        public DbSet<SpecificationAttribute> SpecificationAttribute { get; set; }
        public DbSet<SpecificationAttributeOption> SpecificationAttributeOption { get; set; }
        public DbSet<StateProvince> StateProvince { get; set; }
        public DbSet<Store> Store { get; set; }
        public DbSet<StoreMapping> StoreMapping { get; set; }
        public DbSet<SYS_AppFunction> SYS_AppFunction { get; set; }
        public DbSet<SYS_Apps> SYS_Apps { get; set; }
        public DbSet<SYS_ConfigApp> SYS_ConfigApp { get; set; }
        public DbSet<SYS_ConfigUser> SYS_ConfigUser { get; set; }
        public DbSet<SYS_Function> SYS_Function { get; set; }
        public DbSet<SYS_Menu> SYS_Menu { get; set; }
        public DbSet<SYS_Role> SYS_Role { get; set; }
        public DbSet<SYS_RoleFunction> SYS_RoleFunction { get; set; }
        public DbSet<SYS_User> SYS_User { get; set; }
        public DbSet<SYS_UserRole> SYS_UserRole { get; set; }
        public DbSet<SYS_View> SYS_View { get; set; }
        public DbSet<SYS_ViewFunction> SYS_ViewFunction { get; set; }
        public DbSet<TaxCategory> TaxCategory { get; set; }
        public DbSet<TierPrice> TierPrice { get; set; }
        public DbSet<Topic> Topic { get; set; }
        public DbSet<UrlRecord> UrlRecord { get; set; }
        public DbSet<Vendor> Vendor { get; set; }
        public DbSet<Warehouse> Warehouse { get; set; }
        public DbSet<CostTMP> CostTMP { get; set; }
        public DbSet<CostTmpForUpdate> CostTmpForUpdate { get; set; }
        public DbSet<CurrentCostTMP> CurrentCostTMP { get; set; }
        public DbSet<GiftCard_BK> GiftCard_BK { get; set; }
        public DbSet<GiftCardUsageHistory_BK> GiftCardUsageHistory_BK { get; set; }
        public DbSet<IVM_AdjDetail> IVM_AdjDetail { get; set; }
        public DbSet<vw_RoleMenu> vw_RoleMenu { get; set; }
        public DbSet<POS_SaleOrder> POS_SaleOrder { get; set; }
     */
    }
}
